/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessoesIndexRouteImport } from './routes/sessoes.index'
import { Route as SessoesIdRouteImport } from './routes/sessoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesIndexRoute = SessoesIndexRouteImport.update({
  id: '/sessoes/',
  path: '/sessoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesIdRoute = SessoesIdRouteImport.update({
  id: '/sessoes/$id',
  path: '/sessoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRoute
  '/sessoes/$id': typeof SessoesIdRoute
  '/sessoes/': typeof SessoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRoute
  '/sessoes/$id': typeof SessoesIdRoute
  '/sessoes': typeof SessoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRoute
  '/sessoes/$id': typeof SessoesIdRoute
  '/sessoes/': typeof SessoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/callback' | '/docs' | '/settings' | '/sessoes/$id' | '/sessoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/callback' | '/docs' | '/settings' | '/sessoes/$id' | '/sessoes'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/docs'
    | '/settings'
    | '/sessoes/$id'
    | '/sessoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DocsRoute: typeof DocsRoute
  SettingsRoute: typeof SettingsRoute
  SessoesIdRoute: typeof SessoesIdRoute
  SessoesIndexRoute: typeof SessoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes/': {
      id: '/sessoes/'
      path: '/sessoes'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof SessoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes/$id': {
      id: '/sessoes/$id'
      path: '/sessoes/$id'
      fullPath: '/sessoes/$id'
      preLoaderRoute: typeof SessoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DocsRoute: DocsRoute,
  SettingsRoute: SettingsRoute,
  SessoesIdRoute: SessoesIdRoute,
  SessoesIndexRoute: SessoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
